### ISSUE TITLE
Nested supports collections only 

### ISSUE THREAD

**Issue by blelump** [apotonick/formular#10]
Hi @apotonick ,
sorry I'm just raising issues, but now I have time only for this. 

Formular `nested` does not support single objects (for instance `has_one` relation). I suppose it's due to [`each_with_index`](https://github.com/apotonick/formular/blob/master/lib/formular/builder.rb#L158) as it expects to always get an array.

**Comment by blelump** [comment]
Hi @apotonick ,

I've provided some solution. Please review https://github.com/apotonick/formular/compare/master...blelump:support_nested_object let me know what do you think. I am aware this is far from ideal, but lets start from somewhere.

**Comment by fran-worley** [comment]
This is supported/ fixed in the [new Formular] (https://github.com/trailblazer/formular/)
