### ISSUE TITLE
Render array of hashes for nested collection

### ISSUE THREAD

**Issue by blelump** [apotonick/formular#11]
Hi @apotonick :-) ,

I think it might be another issue, because `builder.nested` renders `{}` for collection instead of `[{},{},{}]`, whereas Reform eats the latter ([see here](https://github.com/apotonick/reform/blob/master/test/populate_test.rb#L67) ).

Here's my attempt to solve it: https://github.com/apotonick/formular/compare/master...blelump:nested_array . Comments are welcome :-) .

**Comment by apotonick** [comment]
Cool, I just got bitten by that myself and remembered there was an issue. :clap:

**Comment by blelump** [comment]
@apotonick , I remember you're having a meeting with Fran on Thursday. I'm really busy last weeks, but I'll try to stress my feelings in an issue here.
