### ISSUE TITLE
Dealing with default control value

### ISSUE THREAD

**Issue by blelump** [apotonick/formular#12]
Hi @apotonick ,

right now, `formular` doesn't prepopulate anything by default. I don't know what's the plan for this, but in case of nested collections, that's a major issue, because it's impossible to set a value for nested element :-) . Each time you create the form builder, it gets the model, so it's accessible. The deal is, how shall we access it (e.g. `attr_reader :model`) or some more generic, like prepopulator idea from Reform.

For now, I'm adding `attr_reader`, but having prepopulator sounds more fancy.

**Comment by apotonick** [comment]
You can simply provide `value: ..` to the `collection` method. 

I'm still working on this part, could you paste a code snippet illustrating your desired API?

**Comment by blelump** [comment]
@apotonick , hi, you're alive :-) .

I'm saying about nested collection given as e.g:
```
f.nested :documents do |g|
  g.input :id, type: :hidden, wrapper: false#, value: xxx – cannot set a value here, because of lack of model object
  g.input :name, value: "I'm nice"
end
```

Ideally I'd say, we shouldn't deal with value, or use it if necessary, because by default, every control field should have default value set, based on record properties. I think it's not kinda `ActionView` magic, because it's useful. The same I'd say about `id` field. Perhaps I've used `form_for` for too long?  :-)

**Comment by fran-worley** [comment]
This shouldn't be an issue in the [new Formular] (https://github.com/trailblazer/formular/) as it value defaults to reader value (simply sending attribute_name to the model).

I'm closing this for now and if I've missed something please raise an issue in the new formular.
