### ISSUE TITLE
Consider builder improvements to provide more readable controls helpers

### ISSUE THREAD

**Issue by blelump** [apotonick/formular#13]
Hi @apotonick ,

consider such form definition:
```
= form(users_path, {model: user, path: %w(user)}, class: ['form-horizontal'], method: :post) do |f|
    = token_tag
    = f.select :program_type_id, program_types, label: I18n.t('label.program_type'), column_attrs: {label_class: ['col-sm-2'], input_class: ['col-sm-6']}, style: :horizontal, checked: user.program_type_id
    = f.select :annual_id, annuals, label: I18n.t('label.academic_year_start'), column_attrs: {label_class: ['col-sm-2'], input_class: ['col-sm-6']}, style: :horizontal, checked: user.annual_id
    = f.select :duration_in_months, duration_of_stay, label: I18n.t('label.duration_of_stay'), column_attrs: {label_class: ['col-sm-2'], input_class: ['col-sm-6']}, style: :horizontal, checked: user.duration_in_months
```

Looks at least "complicated" as every control renderer (`select` in this case) takes tons of params to render what user desires. For instance, thanks to bootstrap builder, we are able to build bootstrap like forms, however on the other hand we extra get `column_attrs: {label_class: ['col-sm-2'], input_class: ['col-sm-6']}, style: :horizontal`. 

I wonder how to deal with that to make it simpler. One solution would be to put those into `form` declaration, however I don't think it's a good idea since such params simply do not belong to form. Besides, there're always edge cases (and I've already got them), where `column_attrs` are not enough. 

So I'm thinking about more generic solution, where user could declare the control format, perhaps in a template, so any use case would be covered.

#### Update

Well, it seems I'm doing smth like that with cells, e.g:
```
class ForeignStudent::Documents::Cell < Cell:Concept
  include App::Formular

  def show
    render layout: :main
  end


  private

  class FileField < self
    inherit_views self.parent

    def show
      render :file_field
    end

    def label
      I18n.t("label.documents.#{name}")
    end
  end
end
```

Such approach does the job, but it's complicated and slightly not reusable in another forms. Now I'm thinking about smth like builder decorator, where you'd declare form fields decorators. Such components (decorators) could be then reused in various parts of the app,, depending of the needs. However, the biggest benefit I'm seeing is that you'd adjust form rendering exactly to the specific needs, including edge cases etc.

**Comment by fran-worley** [comment]
This should be covered by the new Element class system in [new Formular] (https://github.com/trailblazer/formular/). Simply declare your custom control/ input html in an element class and add it to your builder by including it in the element_set hash. If you're struggling with this, please raise a new issue in [new Formular] (https://github.com/trailblazer/formular/).
