### ISSUE TITLE
String/symbol inconsistency for input type file

### ISSUE THREAD

**Issue by blelump** [apotonick/formular#14]
Hi @apotonick , @fran-worley , 

while dealing with input file field, if I type `f.input :ok, type: :file`, it renders `form-control` class, however when type is given as string, e.g `type: 'file'` it doesn't render it. I suppose it's because of this check: https://github.com/apotonick/formular/blob/7b683a3d8d95ebe7958bfa0add0b0bd6c0ae5098/lib/formular/frontend/bootstrap3.rb#L150

**Comment by fran-worley** [comment]
This is resolved in the new-dsl see https://github.com/trailblazer/formular/
