### ISSUE TITLE
Customized controls don't get errors rendered correctly

### ISSUE THREAD

**Issue by blelump** [apotonick/formular#15]
Hi @apotonick , it's me again...

consider such customized file field:
```
.form-group
  = form.label label, class: %w(col-sm-2 control-label)
  .col-sm-4
    .file-picker
      span.icon-upload.for-input
      input.form-control[type="text" placeholder="#{I18n.t('label.pick_new_file')}"]
      = form.input :id, type: :hidden, wrapper: false, value: form.model.id
      = form.input :name, type: :hidden, wrapper: false, value: name
      = form.input :document, type: 'file', wrapper: false
    p.form-control-static = I18n.t("notice.documents.#{name}")
  .col-sm-2
    p.file-label.form-control-static
      span.icon-attachment
      a.file-name[href="#"]
      a.file-del[href="#"]
        span.icon-cross
```

as you'd note, all used form controls have `wrapper: false` to not wrap them into another `div`. This implies, however, that error didn't get `has-error` class and hence all CSS didn't apply.

This is somewhat a continuation of #13 , because both issues essentially touch the same problem – when the scenario is simple, it's fine, but when you get into an edge case, you end with hacks to at least try to make it working.

To sum it up, that builder decorator thing would simplify a lot. In such case, I imagine, I can pass a template like the one above, where the root element (`div.form-group`) is managed by builder and with a template I am able to provide its content, smth like:

```
input_decorator(type: :field) do |builder|
  = builder.label label, class: %w(col-sm-2 control-label)
  .col-sm-4
    .file-picker
      span.icon-upload.for-input
      input.form-control[type="text" placeholder="#{I18n.t('label.pick_new_file')}"]
      = builder.input :id, type: :hidden
      = builder.input :name, type: :hidden
      = builder.input :document, type: 'file'
    p.form-control-static = I18n.t("notice.documents.#{name}")

end
```

#### Update

I like the approach Tim Riley presents [here](https://github.com/icelab/formalist/issues/9) so the above would be rewritten as:

```
define :file_field, from: :input do |input_builder|
  input_builder.template = path_to_a_template or symbol like in cells? 
  input_builder...
end
```

This is definitely still not final.

**Comment by timriley** [comment]
@blelump FYI, I'm no longer going to implement that API idea in formalist. I explained in the last comment on https://github.com/icelab/formalist/issues/9 about why I don't think it's needed anymore.

**Comment by fran-worley** [comment]
@blelump the new formular will make this much easier. I'm going to close this for now and if you are struggling with the new Formular you can raise an issue there.

[new Formular] (https://github.com/trailblazer/formular/)
