### ISSUE TITLE
My 50 cents to the formular future

### ISSUE THREAD

**Issue by blelump** [apotonick/formular#20]
My 50 cents to the Formular design

Background:

I've started to utilize formular 1 or 2 months ago to get rid of any Active* you can think of. Together with Reform (+ dryv) it works quite well, even though there were missing features (e.g. render nested collection and some other minor things). Today I'm still with formular and let me elaborate my feelings about using it:

Formular is a general purpose and framework agnostic form rendering library, with all the strengths and weaknesses, because of such design. To me, the biggest weakness is that it follows the same concept all the Rails dependent predecessors (formtastic and friends) were – very limited possibility to customize its behavior and look and feel. Here, I am genuinely impressed how formalist solves that, because it introduces completely different approach for form rendering. I am not saying about the AST, but the high level API and possibilities to customize my form elements however I need to (or at least I believe it works this way ;-).

Because formular follows the declarative way of customizing form elements, in a real world app, formular form would look smth like:
```
= form(create_learning_agreement_users_path, {model: learning_agreement, path: %w(learning_agreement)}, method: :post) do |f|
  = token_tag
  
  = f.select :program_type_id, program_types, label: I18n.t('label.program_type'), checked: learning_agreement.program_type_id, column_attrs: {label_class: ['col-sm-2'], input_class: ['col-sm-6']}, style: :horizontal, required: :required

  = f.collection :accomodation_id, accomodations, type: :radio, label: I18n.t('label.accomodation'), checked: f.model.accomodation_id, column_attrs: {label_class: ['col-sm-2'], input_class: ['col-sm-6']}, style: :horizontal, required: :required
```

It's complicated, isn't it? A bunch of attributes, where some of them belong to view (`column_attrs`) and some to model (`checked`) just to render simple bootstrap form. The word "simple" is very important here, because formular usually is in troubles once an edge case appears. Forms might be a complex creatures and an easy customizable library would be very appreciated. I'm not saying here about _let's add another option for case z_ approach, but something much more generic, which would not be sticked to any _common_ (currently practiced in most form libraries) boundary. 

Right now I'm still using formular, but my forms look like:
```
= form do |f|
    = token_tag
    = f.select :program_type_id, program_types, label: I18n.t('label.program_type'), checked: learning_agreement.program_type_id

    = f.collection :accomodation_id, accomodations, type: :radio, label: I18n.t('label.accomodation'), checked: f.model.accomodation_id
```

thanks to inheritance of `Formular::Bootstrap3::Builder` and utilizing `dry-configurable`, e.g:

```
class Form < Formular::Bootstrap3::Builder

    extend Dry::Configurable

    setting :default_options, {}
    setting :default_attributes, {}
end
```

It let's me declare a few form types, which are heavily used within my app so I'm able to customize form per use case. However, this is still far from a perfect world, because of API limitations for custom types, e.g I am not able to declare my form types, say `f.my_file_object_with_label_on_bottom` which is styled and customized to serve the form needs.

Summary:

In an ideal world I imagine a form library that provide some basic features and have various, rather type oriented possible customizations instead of adding a bunch of options to the form builder. I think formalist here is a good inspiration how to separate model logic from the view and I'd vote for such approach in formular as well. By splitting model from the view, enduser would be able to decorate his forms according to the design and reuse such logic in all similar forms. I'd also not focus too much on any particular frontend styling library, because user needs always vary and it's just impossible to support all of the use cases. Instead I'd provide a convenient engine that would be easily customized and let one register custom types or style the default ones. Here I believe using some libraries from the `dry` family would be a good choice (I'm thinking about container and configurable).

Having said that, a `Form` class would look like:
```
class Form < Formular::Builder

    configure do
      register :my_file_field, MyFileField
    end
end

class MyFileField < Formular::InputField

  def call(raw_input_field)
    # here input field is wrapped into an desired view logic
    # to present the file field according to the interface assumptions
  end

end

# view.slim:
= Form.new do |f|
  = f.my_file_field
  
  = f.input
```

I'm looking forward for your thoughts.

// cc: @fran-worley @apotonick 

[1]: https://github.com/apotonick/formular/blob/master/lib/formular/builder.rb#L93

**Comment by fran-worley** [comment]
@blelump this is exactly what I want do to. I started using formular and my code ended up looking very similar to SimpleForm.

I have actually made a start on implementing something very much along the lines you have described. I'll post something when I have a bit more.

**Comment by apotonick** [comment]
Very good points, and exactly what my thoughts are. Again, **formular is absolutely not ready** and is only meant as a framework where we put higher abstractions on top. But this time, done right, without any model bindings. I am surprised you already use it, because I wouldn't! :laughing: 

The fundamental design is: provide the necessary classes and graphs and make "everything" configurable via passing options (functional style). This does *not* mean that the end user has to provide all those options everywhere, that's not what I was aiming for.

Instead, and I was working on that in the `model` branch, you'd define defaults and default behavior the way @blelump suggests it, so you have very little to configure. This works via higher abstractions, e.g. the `Bootstrap3` of `Foundation5` classes (just an example).

Totally in for adding custom controls/elements, that was my plan from the very beginning, but I was busy in architecting the essentials and then had to drop the project, because, ya know. :stuck_out_tongue_winking_eye: 

If formalist is what you like better, why don't we work on that one instead? Don't get me wrong, but I've written enough gems in my life and I'm not super keen for Formular, I just thought it's needed, but I'm more than happy to use someone elses work instead.

**Comment by apotonick** [comment]
I couldn't find any formalist docs and checked the specs instead. The question is - do you want a view form builder (Formular/SimleForm) or a declarative one, because we already have that, in Reform. You could then plug "renderers" on top of that.

**Comment by fran-worley** [comment]
@apotonick I'd like to think that there is a middle ground.

The simple_form methodology of passing an ever growing number of options into the view works to a point. 

As @blelump points out, this can quickly get out of hand and your views can get pretty messy.

However I also enjoy the freedom of the fact that it is just a view. I can add arbitrary code etc and see what elements will be in my form right from the view. There is a risk with a more declarative setup that this freedom would be lost or certainly made more difficult.

I think that there is a place for Formular, but for me it needs to be a lot easier to define defaults/ inputs or we are basically building another (albeit faster and more configurable) Simple form.

I spent most of my afternoon working on something like this which I will post once it's a little more polished. 

It is a bit of a departure from the way Formular is written currently, and you may hate it but for me it provides the clarity of the declaration style with the freedom of a traditional form builder.

**Comment by fran-worley** [comment]
Oh and there is a demo formalist app which I have not yet run but have read the code:
https://github.com/icelab/formalist-demo/

**Comment by blelump** [comment]
@apotonick , @fran-worley , 

thanks for your input !! I was completely offline during the weekend, because of friends wedding and hence my late answer.

So we have similar ideas ,  that's great , because together we'd have a stronger abilities to move it forward. The formalist and formular approaches sligthly differ. I mean formalist works on an input hash, whereas formular eats object graph. The form definition is currently used in formalist, see an example [here](https://github.com/icelab/formalist-demo) , I'd recommend to start with smth similar, because it sounds like a very convenient way to deal with any form you'd imagine. However, there's still some work to do because formalist result is just an AST so additional backend renderer has to be implemented. Currently they're heavily utilizing  react so I suppose backend renderer is not the highest priority. 

From my point of view, Formular would duplicate a lot of formalist features, so at least an experiment with formalst would be great start. One thing to consider is a backend renderer, which for sure needs to be elastic and easy to customize, so there's still alot to do.

I'm still really busy, but if you have some spare time, please take a look at formalist, perhaps just a kick ass backend renderer would be enough to change the current approach of dealing with form objects.

**Comment by fran-worley** [comment]
@blelump take a look at the new-dsl branch. It's not exactly usable at the moment but I'd love to hear your comments on the direction.

**Comment by blelump** [comment]
@fran-worley , sorry for being rarely responsive. I definitely like your contributions! The form element DSL simplification / standarization is a good one. As usual :smile: , let me think about the general direction I'd like to have. I have some caveats, but I'm not sure yet how I'd like to solve them. Obviously I'm speaking about `new-dsl` branch. I'll get back to you ASAP.

**Comment by fran-worley** [comment]
@blelump cool. I look forward to hearing from you.

My do-to-list to get it back to where the master branch is:

- [ ] Add support for radios and checkboxes (both individual and groups)
- [ ] Sort out error handling (The code is there it just needs testing)
- [ ] add InputGroups to Bootstrap3 builder
- [ ] HorizontalForms make column classes customisable via an option
- [ ] create a Foundation5 Builder
- [ ] Provide a helper (make it easy to use different builders) e.g. one form might use Bootstrap3 and another Boostrap3Horizontal

**Comment by fran-worley** [comment]
It also provides a fix for the ERB issues and should work perfectly well with or without a model.

**Comment by fran-worley** [comment]
@blelump Have you been able to give this any thought?

**Comment by onemanstartup** [comment]
@apotonick why this library? There this lib https://github.com/jeremyevans/forme with same the same goals it seems. Why not combine efforts?

**Comment by apotonick** [comment]
No idea @onemanstartup, ask @fran-worley ! 😶😓

**Comment by fran-worley** [comment]
@onemanstartup initially, why this library was because I saw what apotonick was trying to do and jumped on the bandwagon. I'd not seen  https://github.com/jeremyevans/forme at the time.

I'd be happy to discuss the options, however the two libs work in very different ways. I think the initial version of formular (master branch) was very similar to Forme, however I've started to pull it into a different direction (new-dsl branch).

It now works in a much more declarative style, by defining elements as classes and combining those classes into builders which in turn create your form. The idea being to be able to create advanced html markup, the kind required by popular frameworks without having view method calls containing every option under the sun. 
The fact that this project doesn't rely on rails to me is a bonus, not the main reason I'm working on it. 

Here you define your elements using pure ruby classes, there is no magic behind how you access them, it's easy to build your own, inherit of a class you like or start from scratch. You can even use it to build elements that aren't anything to do with a form (panels, dropdown buttons etc.). 

Happy to be wrong, but from what I see Forme is essentially 'simple-form' without dependencies and works with or without a model.

**Comment by onemanstartup** [comment]
@fran-worley Thanks for explanation. I am not in position to discuss options 😊. Will try new dsl when will be released, though.

**Comment by blelump** [comment]
Hi @fran-worley !

Sorry for my late reply. As usual, I cannot say more than I don't have much spare time to look at it (I know, it starts to sound annoying). Sorry for that :disappointed: .

1. Re [forme](https://github.com/jeremyevans/forme) gem, I'm having similar feelings to yours. I mean, it solves some form rendering issues (I like that transformers convention), but it still follows the plain-old-magic-form-object where no per form customization is possible. Transformers help, but still have to be used by specifying concrete transormer for particular input.
2. Good to see that you're consequently working on it :smile: . It's really nice to have builder with custom elements list. I'll try to manage some time to play with it!

**Comment by fran-worley** [comment]
@blelump No worries, just checking that you were still interested in the project.

Take a look at https://github.com/fran-worley/gemgem-sinatra/tree/formular-slim-bootstrap3 for a working example of the new branch using the stock bootstrap builders. I'll add some examples of custom elements which will help to clean the views up no end.

You can create your own builder like so:
```ruby
class MyBuilder < Formular::Builders::Basic
  element_set {
    form: FormClass,
    input: InputClass,
    some_other_input: AnotherClass
  }
end
```
The builder defines methods for each element in your element set using the key as the method name and calling the class you pass in.

Elements support full reform style inheritance, including modules for keeping things dry. So it's really easy to just inherit of a class that's nearly there and then register it to your builder by adding it to the `element_set`

**Comment by fran-worley** [comment]
@blelump I'm closing this as we have now moved Formular to [new Formular] (https://github.com/trailblazer/formular/). If you have any further thoughts can you raise an issue in the new repository?
