### ISSUE TITLE
Formular does not capture ERB blocks

### ISSUE THREAD

**Issue by fran-worley** [apotonick/formular#6]
It would appear that currently formular does not correctly capture ERB blocks. 
This code:
```
<%= form action: "/posts", model: model do |f| %>
  ID
  <%= f.input :id %>
  <%= f.textarea :body %>

  <%= f.nested :replies, collection: true do |r| %>
    <%= r.input :email %>
  <% end %>
  
  <%= f.button value: "Submit" %>

  <%= f.input :uuid, value: "0x" %>
<% end %>
```
Should produce:
```
<form action="/posts">
  ID
  <input type="text" name="id" id="form_id" value="1" />
  <textarea name="body" id="form_body">Nice!</textarea>
  <fieldset >
    <input type="text" name="replies[email]" id="form_replies_0_email" value="" />
  </fieldset>
  <input type="button" value="Submit" />
  <input type="text" value="0x" name="uuid" id="form_uuid" />
</form>
```
Instead we get:
```
ID  
<input type="text" name="id" id="form_id" value="1" />  
<textarea name="body" id="form_body">Nice!</textarea>      
<input type="text" name="replies[email]" id="form_replies_0_email" value="" />
<fieldset ></fieldset> 
<input type="button" value="Submit" />  
<input type="text" value="0x" name="uuid" id="form_uuid" />
<form action="/posts"></form>
```

I am working on a fix as we speak. Will let you know if I get anywhere...

**Comment by fran-worley** [comment]
https://github.com/fran-worley/gemgem-sinatra/tree/formular-erb-bootstrap3
For working example.

**Comment by fran-worley** [comment]
There are 2 parts to fixing this issue:

1) make Erbse accept an OB when yielding a content block.

2) create a 'blockless' API for forms that looks something like this:
```
f = form path
  f.input :name, type: :text
  f.textarea, :summary

  n = nested :roles
    n.input :name, type: :text
  n.end
f.end
```

2) can be implemented straight away and will work regardless of engine, but should be optional as other engines do not have the same issues with blocks and when 1) is fixed, you won't have the same problem either.

**Comment by apotonick** [comment]
Option 2), as discussed, is the one we should go for now.

Option 1) is something I'm very keen to work on ASAP, though.

**Comment by fran-worley** [comment]
This fix is included in the new Formular at: https://github.com/trailblazer/formular/
