### ISSUE TITLE
Extend form helper to support path

### ISSUE THREAD

**Issue by blelump** [apotonick/formular#9]
Hi @apotonick ,

perhaps it would be a good idea tu support `Builder` path option from within `Formular::Helper.form` helper, e.g:

```
#view:

= form(create_users_path, {model: user, path: ['blah']}, class: ['form-horizontal'], method: :post) do |f|

# form helper:
def form(url, form_opts = {}, attributes={ method: :post }, &block)
  Formular::Bootstrap3::Builder
  .new(form_opts).form({action: url}.merge(attributes), &block)
end
```

Using `path` sounds reasonable, because it ecapsulates form params. Besides, it's already supported :-) .

**Comment by apotonick** [comment]
Yeah, that was the plan, I just didn't implement it yet. Feel free to PR!

**Comment by blelump** [comment]
@apotonick , I've started working on it, however I'm curious what's the purpose of having singleton class in module `Formular::Helper`? I mean, if a module has a singleton methods, I don't need to include it anywhere (OK, `form` method is indeed an instance method so it needs an inclusion). Could you elaborate?

**Comment by apotonick** [comment]
It's a class method that should not be included into the target class, we only want to import `#form`.

**Comment by blelump** [comment]
Hi @apotonick , 

take a look here https://github.com/apotonick/formular/compare/master...blelump:form-helper and tell me what do you think about it.

**Comment by fran-worley** [comment]
This is covered in the new version of Formular (trailblazer/formular) Though I've called the option path_prefix rather than path.
